version: "2"

services:
  web:
    image: goalgorilla/open_social_docker:dev
    volumes:
     - ./:/var/www
    links:
     - db
#     - mailcatcher
#     - solr
    environment:
     - VIRTUAL_HOST=social.dev
     - DRUPAL_SETTINGS=development
    ports:
     - "80"
    network_mode: "bridge"
    container_name: social_web

  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=social
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306"
    network_mode: "bridge"
    container_name: social_db
    command: mysqld --max_allowed_packet=16M

#  mailcatcher:
#    image: schickling/mailcatcher
#    environment:
#      - VIRTUAL_HOST=mailcatcher.social.dev
#      - VIRTUAL_PORT=1080
#    ports:
#      - "1080"
#    network_mode: "bridge"
#    container_name: social_mailcatcher
#
#  selenium:
#    image: selenium/standalone-firefox-debug:2.48.2
#    volumes:
#      - ./html/profiles/contrib/social/tests/behat/features/files/:/files
#    links:
#     - web:web
#    ports:
#     - "4444"
#     - "5900"
#    cap_add:
#     - NET_ADMIN
#     - NET_RAW
#    network_mode: "bridge"
#    container_name: social_selenium
#
#  behat:
#    image: goalgorilla/open_social_docker:dev
#    volumes:
#     - ./:/var/www
#    links:
#     - web:web
#     - db:db
#     - selenium:selenium
#    environment:
#     - DRUPAL_SETTINGS=development
#    network_mode: "bridge"
#    container_name: social_behat
#
#  cron:
#    image: goalgorilla/open_social_docker:cron
#    volumes:
#     - ./:/var/www
#    links:
#     - db
#     - mailcatcher
#    environment:
#     - DRUPAL_SETTINGS=development
#    network_mode: "bridge"
#    container_name: social_cron
#
#  solr:
#    image: solr:6.6
#    hostname: solr
#    volumes:
#      - os_solr_data:/opt/solr/server/solr/mycores
#      - ./docker/solr/6.x/config_one/:/solr-conf/conf:cached
#    environment:
#      - SOLR_SOLR_MEM_SIZE=512m
#      - PARTIAL_SEARCH_ENABLED=false
#      - VIRTUAL_HOST=solr.social.local
#      - VIRTUAL_PORT=8983
#    ports:
#      - "8983"
#    entrypoint:
#      - solr-precreate
#      - drupal
#      - /solr-conf
#    network_mode: "bridge"
#    container_name: social_solr

volumes:
  db_data:
#  os_solr_data:
